apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: myacgv11f-python 
  janus-idp.io/tekton: myacgv11f-python
  backstage.io/kubernetes-id: myacgv11f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: myacgv11f-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  